### ISSUE TITLE
[✨ Feat]  스와이프 페이지 마무리 작업

### ISSUE THREAD

**Issue by froggy1014** [Swipe-Jeju/swiping-jeju-frontend_v2#12]
## 🛠 Issue

마이그레이션하면서 작업이 너무 커질 것 같아서 앞서서 PR을 먼저 올렸었습니다.

- https://github.com/Swipe-Jeju/swiping-jeju-frontend_v2/pull/11

## 📝 To-do

- [ ] 모달 관련 기능 
- [ ] 제출 버튼 활성화

#### 특정폰트에 대해서 아래 사진과같은 에러 발생 - [0e0f60f](https://github.com/Swipe-Jeju/swiping-jeju-frontend_v2/commit/0e0f60f0c741263d6e830e277b67bed5259c6b39)

- [Reference](https://github.com/vercel/next.js/issues/47115)

|![image](https://github.com/Swipe-Jeju/swiping-jeju-frontend_v2/assets/76844856/3e193d10-3624-4245-89c9-1b90d553e936)|
|:----------------------------------------------------------------------------------------------------------:|

**Comment by seochan99** [comment]
화이팅입니다 ㅎㅅㅎ
