### ISSUE TITLE
[♻️ Refactor] Axios 기본 세팅 및 서비스 코드로의 추상화

### ISSUE THREAD

**Issue by froggy1014** [Swipe-Jeju/swiping-jeju-frontend_v2#22]
## 🛠 Issue

현재 `fetch`로 진행된 데이터 요청 함수를 Axios 서비스 코드로의 추상화 

## 📝 To-do

- [x] axios interceptor 
- [x] fetch related custom hook
- [x] Add metadata
- [x] Test full flow

**Comment by seochan99** [comment]
--- 여기까지 확인 완료!

**Comment by seochan99** [comment]
이슈 닫겠습니당
